### ISSUE TITLE
fix it fast!!!1111!!!11!!

### ISSUE THREAD

**Issue by kuba8888** [akinhet/algorytmy#1]
I do not understand the name of file 'rozkładnaczynniki.py'. Please translate it to english.

**Comment by akinhet** [comment]
POLSKA GUROM!!!!!!! 🇵🇱🇵🇱🇵🇱🇵🇱🇵🇱⛰️⛰️⛰️⛰️⛰️⛰️💪💪💪💪![t2_mariusz_pudzian_pudzianowski_11-1482857515.jpg](https://github.com/akinhet/algorytmy/assets/53797462/d8d25912-af6b-498a-aaff-54e125b9d26b)
